### ISSUE TITLE
How to use them...?

### ISSUE THREAD

**Issue by Tumesc** [JellyBlade/LightdronesContinued#5]
I've made a medical drone v.1, but I can't figure out how to make it work, or if the problem is on my end at all. I've tried placing the drone in the environment, like you would furniture, and I've tried equipping it into an item slot and then using it, like you would a pickaxe. Neither has produced any effect. What am I doing wrong?

**Comment by JellyBlade** [comment]
The Lightdrones are a 'backitem', which means you equip it like the lantern stick on the back slot (where you would put capes). In order for it to produce light or to heal, it has to be in the equip slot, and not the cosmetic slot.

**Comment by Tumesc** [comment]
Thank you!!
